<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dhbw_events"
 *
 * Auto generated by Extension Builder 2016-05-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'dhbw_events',
	'description' => 'Extension for displaying events in different views',
	'category' => 'plugin',
	'author' => 'Florian Löffelad',
	'author_email' => 'loeffelad@dhbw.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);